name: Trigger auto deployment for prudentialfood

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/prudentialfood-AutoDeployTrigger-41629837-131c-4228-84c5-d5022a27ca0c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PRUDENTIALFOOD_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: prudential.azurecr.io
          registryUsername: ${{ secrets.PRUDENTIALFOOD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRUDENTIALFOOD_REGISTRY_PASSWORD }}
          containerAppName: prudentialfood
          resourceGroup: tst
          imageToBuild: prudential.azurecr.io/prudentialfood:${{ github.sha }}
          

     

